
$(document).ready(function(){
    $("#meals").click(function(){
        $("#mealsNumber").fadeIn(1000);
    });
     $("#drinks").click(function(){
        $("#drinksNumber").fadeIn(1000);
    });
       $("#compayments").click(function(){
        $("#compaymentsNumber").fadeIn(1000);
    });
         $("#transport").click(function(){
        $("#transportNumber").fadeIn(1000);
    });
});

$(document).ready(function(){
    $(".button2").click(function(){
        $("#month").show(500);
    });
     $(".button3").click(function(){
        $("#weeks").show(500);
    });
});

$(document).ready(function(){
    $("#button1").click(function(){
        $("#meals").animate({
            top:"300px"
        },1000);
        $("#drinks").animate({
            left:"300px"
        },1000);
        $("#transport").animate({
            left:"700px"
        },1000);
        $("#compayments").animate({
            top:"10px"
        },1000);
    });
});

$(document).ready(function(){
    $("#button2").click(function(){
        $("#meals").animate({
           left:"700px"
        },1000);
        $("#drinks").animate({
            top:"300px"
        },1000);
        $("#transport").animate({
            top:"10px"
        },1000);
        $("#compayments").animate({
            left:"300px"
        },1000);
    });
});

$(document).ready(function(){
    $("#button4").click(function(){
        $("#meals").animate({
           top:"10px"
        },1000);
        $("#drinks").animate({
            left:"700px"
        },1000);
        $("#transport").animate({
            left:"300px"
        },1000);
        $("#compayments").animate({
           top:"300px"
        },1000);
    });
});


$(document).ready(function(){
    $("#button3").click(function(){
        $("#meals").animate({
           left:"300px"
        },1000);
        $("#drinks").animate({
            top:"10px"
        },1000);
        $("#transport").animate({
            top:"300px"
        },1000);
        $("#compayments").animate({
           left:"700px"
        },1000);
    });
});